# Generated by Django 5.0 on 2024-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.CharField(max_length=255, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[(None, 'Género'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=9, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=75, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(db_default=models.Value('No blurb'), verbose_name='Blurb'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(db_default=models.Value('No description'), verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=125, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='org_language',
            field=models.CharField(max_length=125, verbose_name='Original language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='No. of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(verbose_name='Year of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(db_default=models.Value(0), verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='path',
            field=models.FilePathField(verbose_name='Image Path'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(db_default=models.Value('No description'), verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
