# Generated by Django 5.0 on 2024-01-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_avatar_alter_author_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.cover'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='Cover Path'),
        ),
    ]
