# Generated by Django 5.0 on 2024-02-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_path_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url_title',
            field=models.CharField(default='no-title-url', max_length=125, verbose_name='URL Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='Image'),
        ),
    ]
