# Generated by Django 5.0 on 2024-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_url_title_alter_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url_title',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default='no-slug', max_length=125, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
